import "server-only";
import {
  S3Client,
  HeadObjectCommand,
  PutObjectCommand,
  GetObjectCommand,
  DeleteObjectCommand,
  DeleteObjectsCommand,
} from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";

/**
 * Cloudflare R2 client, SERVER-ONLY. `import "server-only"` (already a
 * dependency, used by lib/supabase/service.ts) makes any future client-reachable
 * import fail at build time instead of silently bundling the AWS SDK.
 * (Supersedes the earlier comment here that declined the package.)
 *
 * Checksum settings: recent AWS SDK v3 releases add a default CRC32 checksum to
 * PutObject, which leaks into presigned URLs as x-amz-checksum-* query params
 * and breaks browser PUTs against S3-compatible stores. "WHEN_REQUIRED" is
 * Cloudflare's documented configuration for R2. LIVE R2: UNVERIFIED.
 */
let cachedClient: S3Client | null = null;

function getR2Client(): S3Client {
  if (cachedClient) return cachedClient;

  const accountId = process.env.R2_ACCOUNT_ID;
  const accessKeyId = process.env.R2_ACCESS_KEY_ID;
  const secretAccessKey = process.env.R2_SECRET_ACCESS_KEY;

  if (!accountId || !accessKeyId || !secretAccessKey) {
    throw new Error(
      "R2 credentials are not configured (R2_ACCOUNT_ID / R2_ACCESS_KEY_ID / R2_SECRET_ACCESS_KEY)."
    );
  }

  cachedClient = new S3Client({
    region: "auto",
    endpoint: `https://${accountId}.r2.cloudflarestorage.com`,
    credentials: { accessKeyId, secretAccessKey },
    requestChecksumCalculation: "WHEN_REQUIRED",
    responseChecksumValidation: "WHEN_REQUIRED",
  });
  return cachedClient;
}

function getBucketName(): string {
  const bucket = process.env.R2_BUCKET_NAME;
  if (!bucket) throw new Error("R2_BUCKET_NAME is not configured.");
  return bucket;
}

// Exported so the signed-URL endpoint can report the real TTL to clients.
export const PRESIGNED_PUT_TTL_SECONDS = 300;
export const PRESIGNED_GET_TTL_SECONDS = 300;

/** The key is always server-generated by request_media_upload(). */
export async function createPresignedUploadUrl(
  storageKey: string,
  contentType: string
): Promise<string> {
  const command = new PutObjectCommand({
    Bucket: getBucketName(),
    Key: storageKey,
    ContentType: contentType,
  });
  return getSignedUrl(getR2Client(), command, { expiresIn: PRESIGNED_PUT_TTL_SECONDS });
}

/**
 * Performs NO authorization. Callers must have just resolved storageKey
 * through an RLS-checked media lookup (see media/urls.ts).
 */
export async function createPresignedDownloadUrl(storageKey: string): Promise<string> {
  const command = new GetObjectCommand({ Bucket: getBucketName(), Key: storageKey });
  return getSignedUrl(getR2Client(), command, { expiresIn: PRESIGNED_GET_TTL_SECONDS });
}

/**
 * Verifies an object exists and returns R2's own reported size and content
 * type. Returns null only for a genuine "not found"; anything else throws.
 */
export async function headMediaObject(
  storageKey: string
): Promise<{ sizeBytes: number; contentType?: string } | null> {
  try {
    const result = await getR2Client().send(
      new HeadObjectCommand({ Bucket: getBucketName(), Key: storageKey })
    );
    if (result.ContentLength == null) return null;
    return { sizeBytes: result.ContentLength, contentType: result.ContentType };
  } catch (err: unknown) {
    const e = err as { name?: string; $metadata?: { httpStatusCode?: number } } | null;
    if (e?.name === "NotFound" || e?.name === "NoSuchKey" || e?.$metadata?.httpStatusCode === 404) {
      return null;
    }
    throw err;
  }
}

/** Best-effort single delete. DB is authoritative; never throws. */
export async function deleteMediaObjectBestEffort(
  storageKey: string,
  context?: Record<string, string>
): Promise<void> {
  try {
    await getR2Client().send(
      new DeleteObjectCommand({ Bucket: getBucketName(), Key: storageKey })
    );
  } catch (err) {
    console.error("[storage] best-effort R2 delete failed", { storageKey, ...context, err });
  }
}

const DELETE_BATCH_SIZE = 1000; // S3/R2 DeleteObjects limit
const FALLBACK_CONCURRENCY = 5;

/**
 * Best-effort bulk delete (trip deletion). Uses DeleteObjects in batches of
 * 1000; if a batch call itself fails (e.g. an S3-compat quirk), falls back to
 * single deletes with bounded concurrency. Never throws.
 */
export async function deleteMediaObjectsBestEffort(
  storageKeys: string[],
  context?: Record<string, string>
): Promise<void> {
  for (let i = 0; i < storageKeys.length; i += DELETE_BATCH_SIZE) {
    const chunk = storageKeys.slice(i, i + DELETE_BATCH_SIZE);
    try {
      const res = await getR2Client().send(
        new DeleteObjectsCommand({
          Bucket: getBucketName(),
          Delete: { Objects: chunk.map((Key) => ({ Key })), Quiet: true },
        })
      );
      if (res.Errors && res.Errors.length > 0) {
        console.error("[storage] bulk R2 delete had per-key errors", {
          ...context,
          count: res.Errors.length,
          sample: res.Errors.slice(0, 5),
        });
      }
    } catch (err) {
      console.error("[storage] bulk R2 delete failed; falling back to single deletes", {
        ...context,
        err,
      });
      for (let j = 0; j < chunk.length; j += FALLBACK_CONCURRENCY) {
        await Promise.all(
          chunk
            .slice(j, j + FALLBACK_CONCURRENCY)
            .map((key) => deleteMediaObjectBestEffort(key, context))
        );
      }
    }
  }
}
